FROM python:3.6.1

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements (to leverage Docker cache)
ADD ./requirements.txt /usr/src/app/requirements.txt

# install requirements
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# run server
CMD python events.py runserver -h 0.0.0.0:5001
